API_KEY = 'tYyArpcngqEiz7LxDDKmerdHmHIoOdIAG2Wzl4b82oAfAP94xZyhvvsUTCMmhbfN'
API_SECRET = 'LzFKLXgQYA3Jwkx6KNVNUkematEqlVvyxCMRvv8hnZSZadnTieiwfkTOsRN5a3DU'

telegram_chat_id = '-753037876'
telegram_bot_id = '1805612273:AAGq8OiJBDy1ktg-4MGEVj-7r4H3jE_2nis'

exchange_pairs = [
    'BTCUSDT',
    'HNTUSDT',
    'ETHUSDT',
    'BNBUSDT',
    'NEOUSDT',
    'LTCUSDT',
    'QTUMUSDT',
    'ADAUSDT',
    'XRPUSDT',
    'EOSUSDT',
    'IOTAUSDT',
    'XLMUSDT',
    'ONTUSDT',
    'TRXUSDT',
    'ETCUSDT',
    'ICXUSDT',
    'NULSUSDT',
    'VETUSDT',
    'LINKUSDT',
    'WAVESUSDT',
    'ONGUSDT',
    'HOTUSDT',
    'ZRXUSDT',
    'FETUSDT',
    'BATUSDT',
    'ZECUSDT',
    'IOSTUSDT',
    'CELRUSDT',
    'DASHUSDT',
    'OMGUSDT',
    'THETAUSDT',
    'ENJUSDT',
    'MITHUSDT',
    'MATICUSDT',
    'ATOMUSDT',
    'TFUELUSDT',
    'ONEUSDT',
    'FTMUSDT',
    'ALGOUSDT',
    'GTOUSDT',
    'DOGEUSDT',
    'DUSKUSDT',
    'ANKRUSDT',
    'WINUSDT',
    'COSUSDT',
    'COCOSUSDT',
    'MTLUSDT',
    'TOMOUSDT',
    'PERLUSDT',
    'DENTUSDT',
    'MFTUSDT',
    'KEYUSDT',
    'DOCKUSDT',
    'WANUSDT',
    'FUNUSDT',
    'CVCUSDT',
    'CHZUSDT',
    'BANDUSDT',
    'BEAMUSDT',
    'XTZUSDT',
    'RENUSDT',
    'RVNUSDT',
    'HBARUSDT',
    'NKNUSDT',
    'STXUSDT',
    'KAVAUSDT',
    'ARPAUSDT',
    'IOTXUSDT',
    'RLCUSDT',
    'CTXCUSDT',
    'BCHUSDT',
    'TROYUSDT',
    'VITEUSDT',
    'FTTUSDT',
    'OGNUSDT',
    'DREPUSDT',
    'TCTUSDT',
    'WRXUSDT',
    'BTSUSDT',
    'LSKUSDT',
    'BNTUSDT',
    'LTOUSDT',
    'AIONUSDT',
    'MBLUSDT',
    'COTIUSDT',
    'STPTUSDT',
    'WTCUSDT',
    'DATAUSDT',
    'SOLUSDT',
    'CTSIUSDT',
    'HIVEUSDT',
    'CHRUSDT',
    'ARDRUSDT',
    'MDTUSDT',
    'STMXUSDT',
    'KNCUSDT',
    'REPUSDT',
    'LRCUSDT',
    'PNTUSDT',
    'COMPUSDT',
    'SCUSDT',
    'ZENUSDT',
    'SNXUSDT',
    'VTHOUSDT',
    'DGBUSDT',
    'SXPUSDT',
    'MKRUSDT',
    'DCRUSDT',
    'STORJUSDT',
    'MANAUSDT',
    'YFIUSDT',
    'BALUSDT',
    'BLZUSDT',
    'IRISUSDT',
    'KMDUSDT',
    'JSTUSDT',
    'SRMUSDT',
    'ANTUSDT',
    'CRVUSDT',
    'SANDUSDT',
    'OCEANUSDT',
    'NMRUSDT',
    'DOTUSDT',
    'LUNAUSDT',
    'RSRUSDT',
    'WNXMUSDT',
    'TRBUSDT',
    'SUSHIUSDT',
    'YFIIUSDT',
    'KSMUSDT',
    'EGLDUSDT',
    'DIAUSDT',
    'RUNEUSDT',
    'FIOUSDT',
    'UMAUSDT',
    'BELUSDT',
    'WINGUSDT',
    'UNIUSDT',
    'NBSUSDT',
    'OXTUSDT',
    'SUNUSDT',
    'AVAXUSDT',
    'HNTUSDT',
    'FLMUSDT',
    'ORNUSDT',
    'UTKUSDT',
    'XVSUSDT',
    'ALPHAUSDT',
    'AAVEUSDT',
    'NEARUSDT',
    'FILUSDT',
    'INJUSDT',
    'AUDIOUSDT',
    'CTKUSDT',
    'AKROUSDT',
    'AXSUSDT',
    'HARDUSDT',
    'DNTUSDT',
    'STRAXUSDT',
    'UNFIUSDT',
    'ROSEUSDT',
    'AVAUSDT',
    'XEMUSDT',
    'SKLUSDT',
    'GRTUSDT',
    'JUVUSDT',
    'PSGUSDT',
    '1INCHUSDT',
    'REEFUSDT',
    'OGUSDT',
    'ATMUSDT',
    'ASRUSDT',
    'CELOUSDT',
    'RIFUSDT',
    'BTCSTUSDT',
    'CKBUSDT',
    'TWTUSDT',
    'FIROUSDT',
    'LITUSDT',
    'SFPUSDT',
    'DODOUSDT',
    'CAKEUSDT',
    'ACMUSDT',
    'BADGERUSDT',
    'OMUSDT',
    'PONDUSDT',
    'DEGOUSDT',
    'ALICEUSDT',
    'LINAUSDT',
    'PERPUSDT',
    'CFXUSDT',
    'AUTOUSDT',
    'TKOUSDT',
    'PUNDIXUSDT',
    'TLMUSDT',
    'BTGUSDT',
    'MIRUSDT',
    'BARUSDT',
    'FORTHUSDT',
    'BAKEUSDT',
    'BURGERUSDT',
    'SLPUSDT',
    'ICPUSDT',
    'ARUSDT',
    'POLSUSDT',
    'MDXUSDT',
    'MASKUSDT',
    'XVGUSDT',
    'ATAUSDT',
    'GTCUSDT',
    'ERNUSDT',
    'KLAYUSDT',
    'BONDUSDT',
    'C98USDT',
    'CLVUSDT',
    'QNTUSDT',
    'FLOWUSDT',
    'TVKUSDT',
    'MINAUSDT',
    'RAYUSDT',
    'FARMUSDT',
    'ALPACAUSDT',
    'QUICKUSDT',
    'MBOXUSDT',
    'FORUSDT',
    'REQUSDT',
    'GHSTUSDT',
    'WAXPUSDT',
    'TRIBEUSDT',
    'XECUSDT',
    'ELFUSDT',
    'DYDXUSDT',
    'POLYUSDT',
    'IDEXUSDT',
    'VIDTUSDT',
    'GALAUSDT',
    'ILVUSDT',
    'YGGUSDT',
    'SYSUSDT',
    'DFUSDT',
    'FIDAUSDT',
    'FRONTUSDT',
    'CVPUSDT',
    'AGLDUSDT',
    'RADUSDT',
    'BETAUSDT',
    'RAREUSDT',
    'LAZIOUSDT',
    'CHESSUSDT',
    'ADXUSDT',
    'AUCTIONUSDT',
    'DARUSDT',
    'BNXUSDT',
    'MOVRUSDT',
    'CITYUSDT',
    'ENSUSDT',
    'KP3RUSDT',
    'QIUSDT',
    'PORTOUSDT',
    'POWRUSDT',
    'JASMYUSDT',
    'AMPUSDT',
    'PLAUSDT',
    'PYRUSDT',
    'RNDRUSDT',
    'ALCXUSDT',
]

exchange_pairs_count = {
    'BTCUSDT': {'count': 1, 'ac': False},
    'HNTUSDT': {'count': 1, 'ac': False},
    'ETHUSDT': {'count': 1, 'ac': False},
    'BNBUSDT': {'count': 1, 'ac': False},
    'NEOUSDT': {'count': 1, 'ac': False},
    'LTCUSDT': {'count': 1, 'ac': False},
    'QTUMUSDT': {'count': 1, 'ac': False},
    'ADAUSDT': {'count': 1, 'ac': False},
    'XRPUSDT': {'count': 1, 'ac': False},
    'EOSUSDT': {'count': 1, 'ac': False},
    'IOTAUSDT': {'count': 1, 'ac': False},
    'XLMUSDT': {'count': 1, 'ac': False},
    'ONTUSDT': {'count': 1, 'ac': False},
    'TRXUSDT': {'count': 1, 'ac': False},
    'ETCUSDT': {'count': 1, 'ac': False},
    'ICXUSDT': {'count': 1, 'ac': False},
    'NULSUSDT': {'count': 1, 'ac': False},
    'VETUSDT': {'count': 1, 'ac': False},
    'LINKUSDT': {'count': 1, 'ac': False},
    'WAVESUSDT': {'count': 1, 'ac': False},
    'ONGUSDT': {'count': 1, 'ac': False},
    'HOTUSDT': {'count': 1, 'ac': False},
    'ZRXUSDT': {'count': 1, 'ac': False},
    'FETUSDT': {'count': 1, 'ac': False},
    'BATUSDT': {'count': 1, 'ac': False},
    'ZECUSDT': {'count': 1, 'ac': False},
    'IOSTUSDT': {'count': 1, 'ac': False},
    'CELRUSDT': {'count': 1, 'ac': False},
    'DASHUSDT': {'count': 1, 'ac': False},
    'OMGUSDT': {'count': 1, 'ac': False},
    'THETAUSDT': {'count': 1, 'ac': False},
    'ENJUSDT': {'count': 1, 'ac': False},
    'MITHUSDT': {'count': 1, 'ac': False},
    'MATICUSDT': {'count': 1, 'ac': False},
    'ATOMUSDT': {'count': 1, 'ac': False},
    'TFUELUSDT': {'count': 1, 'ac': False},
    'ONEUSDT': {'count': 1, 'ac': False},
    'FTMUSDT': {'count': 1, 'ac': False},
    'ALGOUSDT': {'count': 1, 'ac': False},
    'GTOUSDT': {'count': 1, 'ac': False},
    'DOGEUSDT': {'count': 1, 'ac': False},
    'DUSKUSDT': {'count': 1, 'ac': False},
    'ANKRUSDT': {'count': 1, 'ac': False},
    'WINUSDT': {'count': 1, 'ac': False},
    'COSUSDT': {'count': 1, 'ac': False},
    'COCOSUSDT': {'count': 1, 'ac': False},
    'MTLUSDT': {'count': 1, 'ac': False},
    'TOMOUSDT': {'count': 1, 'ac': False},
    'PERLUSDT': {'count': 1, 'ac': False},
    'DENTUSDT': {'count': 1, 'ac': False},
    'MFTUSDT': {'count': 1, 'ac': False},
    'KEYUSDT': {'count': 1, 'ac': False},
    'DOCKUSDT': {'count': 1, 'ac': False},
    'WANUSDT': {'count': 1, 'ac': False},
    'FUNUSDT': {'count': 1, 'ac': False},
    'CVCUSDT': {'count': 1, 'ac': False},
    'CHZUSDT': {'count': 1, 'ac': False},
    'BANDUSDT': {'count': 1, 'ac': False},
    'BEAMUSDT': {'count': 1, 'ac': False},
    'XTZUSDT': {'count': 1, 'ac': False},
    'RENUSDT': {'count': 1, 'ac': False},
    'RVNUSDT': {'count': 1, 'ac': False},
    'HBARUSDT': {'count': 1, 'ac': False},
    'NKNUSDT': {'count': 1, 'ac': False},
    'STXUSDT': {'count': 1, 'ac': False},
    'KAVAUSDT': {'count': 1, 'ac': False},
    'ARPAUSDT': {'count': 1, 'ac': False},
    'IOTXUSDT': {'count': 1, 'ac': False},
    'RLCUSDT': {'count': 1, 'ac': False},
    'CTXCUSDT': {'count': 1, 'ac': False},
    'BCHUSDT': {'count': 1, 'ac': False},
    'TROYUSDT': {'count': 1, 'ac': False},
    'VITEUSDT': {'count': 1, 'ac': False},
    'FTTUSDT': {'count': 1, 'ac': False},
    'OGNUSDT': {'count': 1, 'ac': False},
    'DREPUSDT': {'count': 1, 'ac': False},
    'TCTUSDT': {'count': 1, 'ac': False},
    'WRXUSDT': {'count': 1, 'ac': False},
    'BTSUSDT': {'count': 1, 'ac': False},
    'LSKUSDT': {'count': 1, 'ac': False},
    'BNTUSDT': {'count': 1, 'ac': False},
    'LTOUSDT': {'count': 1, 'ac': False},
    'AIONUSDT': {'count': 1, 'ac': False},
    'MBLUSDT': {'count': 1, 'ac': False},
    'COTIUSDT': {'count': 1, 'ac': False},
    'STPTUSDT': {'count': 1, 'ac': False},
    'WTCUSDT': {'count': 1, 'ac': False},
    'DATAUSDT': {'count': 1, 'ac': False},
    'SOLUSDT': {'count': 1, 'ac': False},
    'CTSIUSDT': {'count': 1, 'ac': False},
    'HIVEUSDT': {'count': 1, 'ac': False},
    'CHRUSDT': {'count': 1, 'ac': False},
    'ARDRUSDT': {'count': 1, 'ac': False},
    'MDTUSDT': {'count': 1, 'ac': False},
    'STMXUSDT': {'count': 1, 'ac': False},
    'KNCUSDT': {'count': 1, 'ac': False},
    'REPUSDT': {'count': 1, 'ac': False},
    'LRCUSDT': {'count': 1, 'ac': False},
    'PNTUSDT': {'count': 1, 'ac': False},
    'COMPUSDT': {'count': 1, 'ac': False},
    'SCUSDT': {'count': 1, 'ac': False},
    'ZENUSDT': {'count': 1, 'ac': False},
    'SNXUSDT': {'count': 1, 'ac': False},
    'VTHOUSDT': {'count': 1, 'ac': False},
    'DGBUSDT': {'count': 1, 'ac': False},
    'SXPUSDT': {'count': 1, 'ac': False},
    'MKRUSDT': {'count': 1, 'ac': False},
    'DCRUSDT': {'count': 1, 'ac': False},
    'STORJUSDT': {'count': 1, 'ac': False},
    'MANAUSDT': {'count': 1, 'ac': False},
    'YFIUSDT': {'count': 1, 'ac': False},
    'BALUSDT': {'count': 1, 'ac': False},
    'BLZUSDT': {'count': 1, 'ac': False},
    'IRISUSDT': {'count': 1, 'ac': False},
    'KMDUSDT': {'count': 1, 'ac': False},
    'JSTUSDT': {'count': 1, 'ac': False},
    'SRMUSDT': {'count': 1, 'ac': False},
    'ANTUSDT': {'count': 1, 'ac': False},
    'CRVUSDT': {'count': 1, 'ac': False},
    'SANDUSDT': {'count': 1, 'ac': False},
    'OCEANUSDT': {'count': 1, 'ac': False},
    'NMRUSDT': {'count': 1, 'ac': False},
    'DOTUSDT': {'count': 1, 'ac': False},
    'LUNAUSDT': {'count': 1, 'ac': False},
    'RSRUSDT': {'count': 1, 'ac': False},
    'WNXMUSDT': {'count': 1, 'ac': False},
    'TRBUSDT': {'count': 1, 'ac': False},
    'SUSHIUSDT': {'count': 1, 'ac': False},
    'YFIIUSDT': {'count': 1, 'ac': False},
    'KSMUSDT': {'count': 1, 'ac': False},
    'EGLDUSDT': {'count': 1, 'ac': False},
    'DIAUSDT': {'count': 1, 'ac': False},
    'RUNEUSDT': {'count': 1, 'ac': False},
    'FIOUSDT': {'count': 1, 'ac': False},
    'UMAUSDT': {'count': 1, 'ac': False},
    'BELUSDT': {'count': 1, 'ac': False},
    'WINGUSDT': {'count': 1, 'ac': False},
    'UNIUSDT': {'count': 1, 'ac': False},
    'NBSUSDT': {'count': 1, 'ac': False},
    'OXTUSDT': {'count': 1, 'ac': False},
    'SUNUSDT': {'count': 1, 'ac': False},
    'AVAXUSDT': {'count': 1, 'ac': False},
    'HNTUSDT': {'count': 1, 'ac': False},
    'FLMUSDT': {'count': 1, 'ac': False},
    'ORNUSDT': {'count': 1, 'ac': False},
    'UTKUSDT': {'count': 1, 'ac': False},
    'XVSUSDT': {'count': 1, 'ac': False},
    'ALPHAUSDT': {'count': 1, 'ac': False},
    'AAVEUSDT': {'count': 1, 'ac': False},
    'NEARUSDT': {'count': 1, 'ac': False},
    'FILUSDT': {'count': 1, 'ac': False},
    'INJUSDT': {'count': 1, 'ac': False},
    'AUDIOUSDT': {'count': 1, 'ac': False},
    'CTKUSDT': {'count': 1, 'ac': False},
    'AKROUSDT': {'count': 1, 'ac': False},
    'AXSUSDT': {'count': 1, 'ac': False},
    'HARDUSDT': {'count': 1, 'ac': False},
    'DNTUSDT': {'count': 1, 'ac': False},
    'STRAXUSDT': {'count': 1, 'ac': False},
    'UNFIUSDT': {'count': 1, 'ac': False},
    'ROSEUSDT': {'count': 1, 'ac': False},
    'AVAUSDT': {'count': 1, 'ac': False},
    'XEMUSDT': {'count': 1, 'ac': False},
    'SKLUSDT': {'count': 1, 'ac': False},
    'GRTUSDT': {'count': 1, 'ac': False},
    'JUVUSDT': {'count': 1, 'ac': False},
    'PSGUSDT': {'count': 1, 'ac': False},
    '1INCHUSDT': {'count': 1, 'ac': False},
    'REEFUSDT': {'count': 1, 'ac': False},
    'OGUSDT': {'count': 1, 'ac': False},
    'ATMUSDT': {'count': 1, 'ac': False},
    'ASRUSDT': {'count': 1, 'ac': False},
    'CELOUSDT': {'count': 1, 'ac': False},
    'RIFUSDT': {'count': 1, 'ac': False},
    'BTCSTUSDT': {'count': 1, 'ac': False},
    'CKBUSDT': {'count': 1, 'ac': False},
    'TWTUSDT': {'count': 1, 'ac': False},
    'FIROUSDT': {'count': 1, 'ac': False},
    'LITUSDT': {'count': 1, 'ac': False},
    'SFPUSDT': {'count': 1, 'ac': False},
    'DODOUSDT': {'count': 1, 'ac': False},
    'CAKEUSDT': {'count': 1, 'ac': False},
    'ACMUSDT': {'count': 1, 'ac': False},
    'BADGERUSDT': {'count': 1, 'ac': False},
    'OMUSDT': {'count': 1, 'ac': False},
    'PONDUSDT': {'count': 1, 'ac': False},
    'DEGOUSDT': {'count': 1, 'ac': False},
    'ALICEUSDT': {'count': 1, 'ac': False},
    'LINAUSDT': {'count': 1, 'ac': False},
    'PERPUSDT': {'count': 1, 'ac': False},
    'CFXUSDT': {'count': 1, 'ac': False},
    'AUTOUSDT': {'count': 1, 'ac': False},
    'TKOUSDT': {'count': 1, 'ac': False},
    'PUNDIXUSDT': {'count': 1, 'ac': False},
    'TLMUSDT': {'count': 1, 'ac': False},
    'BTGUSDT': {'count': 1, 'ac': False},
    'MIRUSDT': {'count': 1, 'ac': False},
    'BARUSDT': {'count': 1, 'ac': False},
    'FORTHUSDT': {'count': 1, 'ac': False},
    'BAKEUSDT': {'count': 1, 'ac': False},
    'BURGERUSDT': {'count': 1, 'ac': False},
    'SLPUSDT': {'count': 1, 'ac': False},
    'ICPUSDT': {'count': 1, 'ac': False},
    'ARUSDT': {'count': 1, 'ac': False},
    'POLSUSDT': {'count': 1, 'ac': False},
    'MDXUSDT': {'count': 1, 'ac': False},
    'MASKUSDT': {'count': 1, 'ac': False},
    'XVGUSDT': {'count': 1, 'ac': False},
    'ATAUSDT': {'count': 1, 'ac': False},
    'GTCUSDT': {'count': 1, 'ac': False},
    'ERNUSDT': {'count': 1, 'ac': False},
    'KLAYUSDT': {'count': 1, 'ac': False},
    'BONDUSDT': {'count': 1, 'ac': False},
    'C98USDT': {'count': 1, 'ac': False},
    'CLVUSDT': {'count': 1, 'ac': False},
    'QNTUSDT': {'count': 1, 'ac': False},
    'FLOWUSDT': {'count': 1, 'ac': False},
    'TVKUSDT': {'count': 1, 'ac': False},
    'MINAUSDT': {'count': 1, 'ac': False},
    'RAYUSDT': {'count': 1, 'ac': False},
    'FARMUSDT': {'count': 1, 'ac': False},
    'ALPACAUSDT': {'count': 1, 'ac': False},
    'QUICKUSDT': {'count': 1, 'ac': False},
    'MBOXUSDT': {'count': 1, 'ac': False},
    'FORUSDT': {'count': 1, 'ac': False},
    'REQUSDT': {'count': 1, 'ac': False},
    'GHSTUSDT': {'count': 1, 'ac': False},
    'WAXPUSDT': {'count': 1, 'ac': False},
    'TRIBEUSDT': {'count': 1, 'ac': False},
    'XECUSDT': {'count': 1, 'ac': False},
    'ELFUSDT': {'count': 1, 'ac': False},
    'DYDXUSDT': {'count': 1, 'ac': False},
    'POLYUSDT': {'count': 1, 'ac': False},
    'IDEXUSDT': {'count': 1, 'ac': False},
    'VIDTUSDT': {'count': 1, 'ac': False},
    'GALAUSDT': {'count': 1, 'ac': False},
    'ILVUSDT': {'count': 1, 'ac': False},
    'YGGUSDT': {'count': 1, 'ac': False},
    'SYSUSDT': {'count': 1, 'ac': False},
    'DFUSDT': {'count': 1, 'ac': False},
    'FIDAUSDT': {'count': 1, 'ac': False},
    'FRONTUSDT': {'count': 1, 'ac': False},
    'CVPUSDT': {'count': 1, 'ac': False},
    'AGLDUSDT': {'count': 1, 'ac': False},
    'RADUSDT': {'count': 1, 'ac': False},
    'BETAUSDT': {'count': 1, 'ac': False},
    'RAREUSDT': {'count': 1, 'ac': False},
    'LAZIOUSDT': {'count': 1, 'ac': False},
    'CHESSUSDT': {'count': 1, 'ac': False},
    'ADXUSDT': {'count': 1, 'ac': False},
    'AUCTIONUSDT': {'count': 1, 'ac': False},
    'DARUSDT': {'count': 1, 'ac': False},
    'BNXUSDT': {'count': 1, 'ac': False},
    'MOVRUSDT': {'count': 1, 'ac': False},
    'CITYUSDT': {'count': 1, 'ac': False},
    'ENSUSDT': {'count': 1, 'ac': False},
    'KP3RUSDT': {'count': 1, 'ac': False},
    'QIUSDT': {'count': 1, 'ac': False},
    'PORTOUSDT': {'count': 1, 'ac': False},
    'POWRUSDT': {'count': 1, 'ac': False},
    'JASMYUSDT': {'count': 1, 'ac': False},
    'AMPUSDT': {'count': 1, 'ac': False},
    'PLAUSDT': {'count': 1, 'ac': False},
    'PYRUSDT': {'count': 1, 'ac': False},
    'RNDRUSDT': {'count': 1, 'ac': False},
    'ALCXUSDT': {'count': 1, 'ac': False},
}
